### ISSUE TITLE
enabled plugin caused 1-2 sec delay for typing

### ISSUE THREAD

**Issue by castamir** [juzna/intellij-nette#12]
plugin works just fine in a nette sandbox, but it causes delay (1+2 sec) in bigger projects

**Comment by neuro159** [comment]
can you please provide some kind of fixed scenario to reproduce?

**Comment by castamir** [comment]
@neuro159 it has been over 3 years and I'm not using this plugin any more

**Comment by JanTvrdik** [comment]
@castamir Maybe close the issue then? It can be reopened if someone else encounters this problem.

**Comment by JanTvrdik** [comment]
Closing this issue, it can be reopened if someone else encounters this problem.
