### ISSUE TITLE
IDE complains when accessing private properties with getter using Nette\Object magic

### ISSUE THREAD

**Issue by maryo** [juzna/intellij-nette#21]
Given there is this code.

``` php
class Foo extends Nette\Object
{
    private $bar;

    public function getBar()
    {
        return $this->bar;
    }
}

$foo = new Foo;
echo $foo->bar; // IDE complains "Member has private access, but class has magic method __get"
```

I think it would be better if this message did not appear since the class has the getter. Is it a good idea, bad idea or a bug? OfC I'm not sure it's easy/possible to do.

**Comment by matej21** [comment]
It is not easy to suppress those messages, but I will try :)

**Comment by matej21** [comment]
Magic properties without `@property` annotation are deprecated since nette 2.4, so this issue is not relevant anymore.
