### ISSUE TITLE
Calling filters on variables inspection

### ISSUE THREAD

**Issue by ajaxovic** [juzna/intellij-nette#31]
Calling filters on variable is possible from version 2.4
https://forum.nette.org/cs/26250-pojdte-otestovat-nette-2-4-rc

Plugin still says "Modifiers are not allowed here".
![image](https://user-images.githubusercontent.com/11288002/69415660-51702600-0d15-11ea-93e1-fe76ffb5aa45.png)

**Comment by matej21** [comment]
hi, you are in a wrong repo. please submit an issue here: https://github.com/jantvrdik/intellij-latte

**Comment by ajaxovic** [comment]
Ahhh, sorry :(
